### ISSUE TITLE
Definições sobre a logo do projeto

### ISSUE THREAD

**Issue by FranWeidt** [UniAcademia/Sistema-de-adocao-de-Animais-I#1]
**Gente, o que vocês acham de fazermos uma logo baseada nesta aqui:**

![image](https://user-images.githubusercontent.com/6913867/93651196-01222d00-f9e7-11ea-8714-0e5a669819ef.png)

E aí @toledkrw ? O que acha?

**Comment by toledkrw** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at dui sed ante porta commodo vel id risus. Cras sagittis eros ut eros laoreet!
